version: "3"

services:
  helloserver:
    build: ./build/server
    container_name: helloserver
    environment:
      SC_ADDRESS: "service-center"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./build/server/conf/chassis.yaml:/data/conf/chassis.yaml
      - ./build/server/conf/microservice.yaml:/data/conf/microservice.yaml
    networks:
      aomi:
        ipv4_address: 172.27.0.101
  
  helloclient:
    build: ./build/client
    container_name: helloclient
    environment:
      SC_ADDRESS: "service-center"
    ports:
      - "2002:2002"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./build/client/conf/chassis.yaml:/data/conf/chassis.yaml
      - ./build/client/conf/microservice.yaml:/data/conf/microservice.yaml
    networks:
      aomi:
        ipv4_address: 172.27.0.102

networks:
  aomi:
    external: true